server:
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000 #最大连接数
    max-connections: 20000 #最大并发数

spring:
  application:
    name: jee
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      #SpringBoot 文件上传、下载、设置大小.限制大小30MB
      max-file-size: 30MB
      max-request-size: 30MB
      #如果不限制大小，则设置为-1即可
      #maxFileSize: -1
      #maxRequestSize: -1
  #数据库的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql
    driverClassName: com.mysql.jdbc.Driver
    druid:
        url: jdbc:mysql://127.0.0.1:3306/learner?useUnicode=true&characterEncoding=utf-8
        #oracle
        #driverClassName: oracle.jdbc.driver.OracleDriver
        #jdbc:oracle:thin:@127.0.0.1:1521:orcl
        username: root
        password: root
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 3
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 30000
        validationQuery: SELECT 'x' FROM DUAL
        #SqlServer要配置为 select 1
        #validationQuery: select 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            #login-username: admin
            #login-password: admin
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filter:
            stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: false
            wall:
                config:
                    multi-statement-allow: true
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true

#logging
logging:
  level: debug
  level.com.sinopec.fos: debug
  level.org.springframework.web: debug
  level.org.springboot.sample: debug
  level.com.jee.service.sys.dao: debug
  path: logs/
#spring-ehcache的配置

#mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:/mappings/**/*.xml
  type-aliases-package: com.jee.service.sys.entity

# Shiro权限配置
shiro:
  redis: false #启动shiro redis缓存，单点登录,##单点登录性能有带提升##
  user:
    # 登录地址
    loginUrl: /admin/login
    # 权限认证失败地址
    unauthorizedUrl: /admin/login
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10