spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/jeelearn_miaosha?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: root
            primary:  #数据源1
                url: jdbc:mysql://localhost:3306/jeelearn_miaosha?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: root
            secondary:  #数据源2
                url: jdbc:mysql://10.168.46.213:3306/FOS3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    redis:
      open: false  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 10.178.46.205
      port: 6379
      password:    # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接

    #ldap配置
    ldap:
        urls: ldap://10.168.3.55:389/
        username: imc.glgy
        password: imc.glgy
fos:
  wsdl:
    fos: 10.177.1.35:10000
    cmc:
    alarm: